### ISSUE TITLE
RStudio (1.0.143) Add-in not opening in OS X 10.11.6

### ISSUE THREAD

**Issue by rubgb** [matloff/revisit#1]
I installed the package using `install_github("matloff/revisit")`
but when I tried to load the add-in I got the following error message:

Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") :
  cannot open file 'R/revisit.css': No such file or directory

**Comment by rdavis27** [comment]
Hi rubgb,

I'll try installing using install_github and see if I can find the best solution to the problem.  I've been running in a development environment where the file revisit.css is in the subdirectory R of the current working directory.  You can check the current directory by typing getwd() in the console.  If you do see that you have the revisit.css file, try putting it in a subdirectory named R in the current directory.

Meanwhile, I'll try install_github and see if I can find a better solution so that others don't experience this problem.  Please let me know if this continues to be a problem.  I should likely have a solution within an hour or two.

Thanks,
Reed Davis

**Comment by rubgb** [comment]
Hi Reed,
thanks a lot for the suggestion. I manually downloaded and saved "revisit.css" in a subdirectory named "R" under my working directory and now it works fine.

**Comment by rdavis27** [comment]
That's great to hear, rubgb!  Let me know if you have any other problems or questions.  Meanwhile, I'm going to look at implementing a fix so that others don't run into this problem.  Thanks for the heads up.
Reed

**Comment by rdavis27** [comment]
Hi rubgb,
I've checked in a fix so that revisit.css is no longer required.  However, you will need to keep using it unless and until to download the fix.  There's no rush for you to do so right now as everything should work exactly the same.  Anyhow, please let me know if you run into any problems.  I'm going to mark this issue closed.
Reed
